
### 请求接口
GET http://localhost:8080/course/course/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ5b3VuZ3hodWkiLCJzY29wZSI6WyJhbGwiXSwiaWQiOjEsImV4cCI6MTYwNDcxODUxMCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiY2I5ODIyMTktM2JkNC00ZDU4LWIyMjMtMjYyMDRiMTY3Y2EzIiwiY2xpZW50X2lkIjoiY2xpZW50LWFwcCJ9.DqTtgScsG5U2GEqillIQJor34S5FVHcqN8Vc8QuV1_FFkIcraqTC4xtKn87G99g-E0vGWH8ObL-aigRyMxWWAoT8YV5i_JcPRIXbljH1i0urBQKBSV9s7nYyYIID-yKziolS9uhQScq8MUgR7TT3dI6i42pgCXYK5OcTcDxlMIg

### 授权
POST http://localhost:8024/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=client-app&client_secret=123456&username=youngxhui@gmail.com&password=123456
